categories = {
    "Food": [
        "SAUBELS MARKET", 
        "ALDI", 
        "YORK GROCERY OUTLET", 
        "BBS GROCE",
        "CHICK-FIL-A",
        "TST* WIRED CUP",
        "AUNTIEANNES",
        "ROHRERSTOWN GRO",
        "GIANT",
        "CHIPOTLE",
        "CHARLESTON COFFEE",
        "TRADER JOE",
        "FOOD LION",
        "WENDYS",
        "THE BUBBLE ROOM",
        "SMOOTHIE KING",
        "PUBLIX",
        "COOL DOUGH",
        "EVANS ORCHARD",
        "KROGER",
        "GRAETERS",
        "PANERA BREAD",
        "LEG UP FARMERS",
        "MARKET HOUSE PICKL",
        "MONTE CARLO PIZZA",
        "THE FRESH MARKET",
        "WHOLEFDS",
    ],
    "Health": [
        "CVS/PHARM",
        "HEALTHCARE",
        "MIDWAY FAMILY DENTAL",
        "WWW.CLEARLYFILTERED.CO",
        "LEXINGTON ENDODONTICS",
        "Zion Health",
    ],
    "Utilities": [
        "COMCAST", 
        "ENTEGRO LLC", 
        "Buttonwood",
        "FIRSTENERGY",
    ],
    "Housing": [
        "BUTTONWOOD GARDENS",
        "Qbe insurance",
        "airdoctor",
    ],
    "Transportation": [
        "SHEETZ", 
        "TURKEY HILL",
        "COLUMBIA GAS",
        "FSI KY FARM BUREAU",
        "RUTTER",
        "BP#",
        "ADVANCE AUTO PARTS",
        "CIRCLE K",
        "SUNOCO",
        "RACETRAC",
        "PARKERS",
        "SHELL SERVICE STATION",
        "Shell oil",
        "GO MART",
        "MARATHON PETRO",
        "Speedway",
        "Yorkshire garage",
    ],
    "Shopping": [
        "PRICERITE YORK", 
        "Finders Keepers",
        "Fashion Cents",
        "MERCARI",
        "GABRIEL BROS",
        "COMMUNITYAID",
        "ABERCROMBIE &amp; FITCH",
        "BURLINGTON",
        "THRIFT",
        "MARSHALLS",
        "TARGET",
        "Amazon.com",
        "AMZN",
        "GOODWILL",
        "ROSS STORES",
        "OLLIES BARGAIN OUTLET",
        "THE HOME DEPOT",
        "DOLLAR-GE",
        "Forever 21",
        "TJMAXX",
        "OLD NAVY",
        "WM SUPERCENTER",
        "Newegg",
        "Ebay",
        "BED BATH &amp; BEYOND",
        "BEDBATH&amp;BEYOND",
        "THE SALVATION ARMY",
        "Etsy.com",
        "Framework*",
        "Dollar tree",
    ],
    "Education": [
        "FIRSTMARK",
    ],
    '"Vacation, Holiday, Events, and Traveling"': [
        "Leewaysvcctrviolatione",
    ],
    "Baby": [
        "rebelstork",
        "WOMENS HEALTH SERVICES",
    ],
    "Entertainment": [
        "SPOTIFY", 
        "SOUTH YORK CINEMA",
    ],
    "Misc": [
        "Check Paid",
        "USPS",
        "WAL-MART",
        "WALMART",
        "Wal-Mart",
    ],
}

exclude_list = [
    "TD AMERITRADE", 
    "LIBERTY UNIVER",
    "NAKUPUNA SOLUTIO",
    "2022 Roth IRA Contribution Vault",
    "SoFi Credit Card",
    "Interest earned",
    "To Savings",
    "From 2023 House Down Payment Vault",
    "WELLS FMARGO",
    "SOFI BANK",
    "WHITAKER BANK",
    "COINBASE",
    "SOFI SECURITIES",
    "Mobile Check Deposit",
    "SOFI CREDIT CORP",
    "Payment - thank you",
    "Alpaca",
    "Digitalocean.com",
    "DIRECTPAY",
    "DISCOVER",
    "VENMO", 
    "Auto-pay thank you",
]